@startuml shopping
[front end] as Front_end
[Login and Register] as Li
[Order] as Order
[Inquire] as Inquire
[Shopping] as Shopping
[commodity management] as Management
[User database] as UserDatabase
[Product database] as ProductDatabase
[Order database] as OrderDatabase
[pay] as Pay

Front_end --( HTTPS
HTTPS -- Li
HTTPS -- Inquire
HTTPS -- Shopping
HTTPS --  Order

Order ..> Shopping
Inquire ..> Li
Shopping ..> Inquire
Shopping ..> Pay
Shopping ..> Management

Li --( UserDataBaseAPi
Inquire --( ProductDataBaseAPi
Shopping --( OrderDataBaseAPi
Management --( OrderDataBaseAPi
Order --( OrderDataBaseAPi

UserDatabase -- UserDataBaseAPi
ProductDatabase -- ProductDataBaseAPi
OrderDatabase -- OrderDataBaseAPi

@enduml